services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  backend:
    image: edon505/daystride-backend:latest

    depends_on:
      db:
        condition: service_healthy

    restart: on-failure:6
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONTEND_HOST=frontend
      - FRONTEND_PORT=80
      - DJANGO_SECRET=${DJANGO_SECRET}

  frontend:
    image: edon505/daystride-frontend:latest
    restart: on-failure:6
    environment:
      - VITE_BACKEND_HOST=http://backend:8080/api/
    ports:
      - "80:80"
