# Generated by Django 5.2.3 on 2025-06-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='deadline',
        ),
        migrations.AddField(
            model_name='todotask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
