name: Dev Testing Pipeline

on:
  workflow_dispatch:

jobs:
  dev-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build and start containers
      run: |
        docker compose up -d

    - name: Run backend integration tests
      run: |
        docker compose exec backend pytest -m integration_large --disable-warnings --tb=short

    - name: Run frontend integration tests
      run: |
        docker compose exec frontend npm run test:integration-itl

    - name: Dump backend logs on failure
      if: failure()
      run: |
        echo "==== Backend Logs ===="
        docker compose logs backend

    - name: Dump frontend logs on failure
      if: failure()
      run: |
        echo "==== Frontend Logs ===="
        docker compose logs frontend

    - name: Tear down
      if: always()
      run: docker compose down --volumes
