name: Dev Testing Pipeline

on:
  workflow_dispatch:

jobs:
  dev-testing:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.7
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose
      uses: docker/setup-compose-action@v3

    - name: Build and start containers
      run: |
        docker compose up -d

    - name: Run backend integration tests
      run: |
        docker compose exec backend pytest -m integration_large --disable-warnings --tb=short

    - name: Run frontend integration tests
      run: |
        docker compose exec frontend npm run test:integration-itl

    - name: Tear down
      if: always()
      run: docker compose down --volumes
