name: Security Test - ZAP DAST Scan on EC2

on:
  workflow_run:
    workflows: [ 'K6 Load Testing Pipeline' ]
    types:
      - completed
  workflow_dispatch:

jobs:
  zap_scan:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "${{ vars.EC2_PUBLIC_IP }}"
          cmd_options: "-a"  # active scan for aggressive checks
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
